import header from '../img/1111_logo.svg'
import footerLogo from '../img/footer_logo.png'
import footerSocial01 from '../img/facebook-icon.svg'
import footerSocial02 from '../img/line-icon.svg'
import footerSocial03 from '../img/twitter-icon.svg'
import footerToTop from '../img/goToTop.svg'
import jobCard from '../img/job-card-cover.png'
import jobCardIcon01 from '../img/job-card-icon01.png'
import jobCardIcon02 from '../img/job-card-icon02.png'
import articleSection from '../img/article-cover.png'
import archive_img from '../img/archive-ex-img.png'
import pgnb2 from '../img/pgnb-style2-arrow.svg'
import swiperImg from '../img/swiper-img.png'
import categoryImg from '../img/category-img.png'
import logo_ex from '../img/brand-ex.png'
<<<<<<< HEAD
import file_icon from '../img/input-file.svg'
=======
import categoryItem01 from '../img/category-item01.png'
import categoryItem02 from '../img/category-item02.png'
import categoryItem03 from '../img/category-item03.png'
import categoryItem04 from '../img/category-item04.png'
import categoryItem05 from '../img/category-item05.png'
import categoryItem06 from '../img/category-item06.png'
import categoryItem07 from '../img/category-item07.png'
import categoryItem08 from '../img/category-item08.png'
import categoryItem09 from '../img/category-item09.png'
import categoryItem10 from '../img/category-item10.png'
import categoryItem11 from '../img/category-item11.png'
import ad from '../img/ad-ex.png'
>>>>>>> b363e5364adc9c4714fbe3f36654f68fc40020a1
